
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABBR BEGINSQUAD BRACKETS C CLOSEABBR CLOSEBODY CLOSEBRACKETS CLOSEDATA CLOSEHEAD CLOSEHREF CLOSEROW CONTENT GARBAGE OPENBODY OPENDATA OPENHEAD OPENHREF OPENROW VCstart : initinit : before BEGINSQUAD skip OPENBODY rows CLOSEBODYbefore : CONTENT before\n              | OPENBODY before\n              | CLOSEBODY before\n              | OPENHEAD before\n              | CLOSEHEAD before\n              | OPENDATA before\n              | CLOSEDATA before\n              | OPENHREF before\n              | CLOSEHREF before\n              | OPENROW before\n              | CLOSEROW before\n              | rows : OPENROW OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD CLOSEROW rows\n            | OPENROW columns CLOSEROW rows\n            | columns : OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENHEAD OPENHREF CONTENT CLOSEHREF CLOSEHEAD OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA\n               | OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENHEAD OPENHREF CONTENT CLOSEHREF CONTENT skip CLOSEHEAD OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA\n               | OPENDATA CLOSEDATAskip : CONTENT skip\n            | OPENHREF skip\n            | CLOSEHREF skip\n            | '
    
_lr_action_items = {'CONTENT':([0,4,5,6,7,8,9,10,11,12,13,14,15,28,29,30,38,40,48,49,54,57,60,61,63,67,68,72,76,77,81,85,86,90,94,99,],[6,6,6,6,6,6,6,6,6,6,6,6,28,28,28,28,41,28,50,28,56,59,62,63,28,28,71,28,28,80,28,28,89,28,28,28,]),'OPENBODY':([0,4,5,6,7,8,9,10,11,12,13,14,15,27,28,29,30,32,33,34,],[4,4,4,4,4,4,4,4,4,4,4,4,-24,31,-24,-24,-24,-21,-22,-23,]),'CLOSEBODY':([0,4,5,6,7,8,9,10,11,12,13,14,31,35,42,46,95,98,],[5,5,5,5,5,5,5,5,5,5,5,5,-17,37,-17,-16,-17,-15,]),'OPENHEAD':([0,4,5,6,7,8,9,10,11,12,13,14,36,45,52,53,58,65,74,83,],[7,7,7,7,7,7,7,7,7,7,7,7,38,48,54,55,60,68,77,86,]),'CLOSEHEAD':([0,4,5,6,7,8,9,10,11,12,13,14,28,29,30,32,33,34,41,50,56,61,62,63,66,71,80,89,],[8,8,8,8,8,8,8,8,8,8,8,8,-24,-24,-24,-21,-22,-23,45,52,58,64,65,-24,69,74,83,92,]),'OPENDATA':([0,4,5,6,7,8,9,10,11,12,13,14,36,47,64,69,73,78,82,87,91,96,],[9,9,9,9,9,9,9,9,9,9,9,9,40,49,67,72,76,81,85,90,94,99,]),'CLOSEDATA':([0,4,5,6,7,8,9,10,11,12,13,14,28,29,30,32,33,34,40,43,49,51,67,70,72,75,76,79,81,84,85,88,90,93,94,97,99,101,],[10,10,10,10,10,10,10,10,10,10,10,10,-24,-24,-24,-21,-22,-23,44,47,-24,53,-24,73,-24,78,-24,82,-24,87,-24,91,-24,96,-24,100,-24,102,]),'OPENHREF':([0,4,5,6,7,8,9,10,11,12,13,14,15,28,29,30,40,49,55,63,67,72,76,81,85,90,94,99,],[11,11,11,11,11,11,11,11,11,11,11,11,29,29,29,29,29,29,57,29,29,29,29,29,29,29,29,29,]),'CLOSEHREF':([0,4,5,6,7,8,9,10,11,12,13,14,15,28,29,30,40,49,59,63,67,72,76,81,85,90,94,99,],[12,12,12,12,12,12,12,12,12,12,12,12,30,30,30,30,30,30,61,30,30,30,30,30,30,30,30,30,]),'OPENROW':([0,4,5,6,7,8,9,10,11,12,13,14,31,42,95,],[13,13,13,13,13,13,13,13,13,13,13,13,36,36,36,]),'CLOSEROW':([0,4,5,6,7,8,9,10,11,12,13,14,39,44,92,100,102,],[14,14,14,14,14,14,14,14,14,14,14,14,42,-20,95,-18,-19,]),'BEGINSQUAD':([0,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,],[-14,15,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-14,-4,-5,-3,-6,-7,-8,-9,-10,-11,-12,-13,]),'$end':([1,2,37,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'init':([0,],[2,]),'before':([0,4,5,6,7,8,9,10,11,12,13,14,],[3,16,17,18,19,20,21,22,23,24,25,26,]),'skip':([15,28,29,30,40,49,63,67,72,76,81,85,90,94,99,],[27,32,33,34,43,51,66,70,75,79,84,88,93,97,101,]),'rows':([31,42,95,],[35,46,98,]),'columns':([36,],[39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> init','start',1,'p_start','nationyacc.py',81),
  ('init -> before BEGINSQUAD skip OPENBODY rows CLOSEBODY','init',6,'p_init','nationyacc.py',84),
  ('before -> CONTENT before','before',2,'p_before','nationyacc.py',87),
  ('before -> OPENBODY before','before',2,'p_before','nationyacc.py',88),
  ('before -> CLOSEBODY before','before',2,'p_before','nationyacc.py',89),
  ('before -> OPENHEAD before','before',2,'p_before','nationyacc.py',90),
  ('before -> CLOSEHEAD before','before',2,'p_before','nationyacc.py',91),
  ('before -> OPENDATA before','before',2,'p_before','nationyacc.py',92),
  ('before -> CLOSEDATA before','before',2,'p_before','nationyacc.py',93),
  ('before -> OPENHREF before','before',2,'p_before','nationyacc.py',94),
  ('before -> CLOSEHREF before','before',2,'p_before','nationyacc.py',95),
  ('before -> OPENROW before','before',2,'p_before','nationyacc.py',96),
  ('before -> CLOSEROW before','before',2,'p_before','nationyacc.py',97),
  ('before -> <empty>','before',0,'p_before','nationyacc.py',98),
  ('rows -> OPENROW OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD OPENHEAD CONTENT CLOSEHEAD CLOSEROW rows','rows',24,'p_rows','nationyacc.py',101),
  ('rows -> OPENROW columns CLOSEROW rows','rows',4,'p_rows','nationyacc.py',102),
  ('rows -> <empty>','rows',0,'p_rows','nationyacc.py',103),
  ('columns -> OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENHEAD OPENHREF CONTENT CLOSEHREF CLOSEHEAD OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA','columns',23,'p_columns','nationyacc.py',106),
  ('columns -> OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENHEAD OPENHREF CONTENT CLOSEHREF CONTENT skip CLOSEHEAD OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA OPENDATA skip CLOSEDATA','columns',25,'p_columns','nationyacc.py',107),
  ('columns -> OPENDATA CLOSEDATA','columns',2,'p_columns','nationyacc.py',108),
  ('skip -> CONTENT skip','skip',2,'p_skip','nationyacc.py',113),
  ('skip -> OPENHREF skip','skip',2,'p_skip','nationyacc.py',114),
  ('skip -> CLOSEHREF skip','skip',2,'p_skip','nationyacc.py',115),
  ('skip -> <empty>','skip',0,'p_skip','nationyacc.py',116),
]
